### ISSUE TITLE
`list_chains` event only returns those chains which have `clean_on_stop: false`

### ISSUE THREAD

**Issue by sirromdev** [makerdao/ex_testchain#33]

**Comment by tomedwardsmith** [comment]
Hi @sirromdev is this a bug or a feature request?

**Comment by sirromdev** [comment]
Hmm, I'm unsure as I don't know how exactly `list_chains` works but I suppose you could call it a feature request.

What I've noticed with the testchain-client is that the list_chains event will only list those chains that were configured with `clean_on_stop: false`. It will list any of these chains which are `active` or `inactive`. Where a chain is configured with `clean_on_stop: true` and the chain is actively running, (if not it will be deleted as per the `clean_on_stop` rule), `list_chains` will not list it as present.

If this is not clear, I could model it with the client but we do have a workaround in place that suffices for the time being since the introduction of the REST api.

**Comment by konstantinzolotarev** [comment]
@sirromdev @tomedwardsmith Should be fixed with last updates. New docker image pushed to Docker hub.

**Comment by sirromdev** [comment]
I've pulled the latest changes @konstantinzolotarev and it doesn't appear to have changed? I'm pushing `'list_chains'` on the api channel but the response is still the same.
